// In this models folders, we will create different models that we will need in this project
// Different models means different collections in our database.
// Here this is the model for 'listing' 
// Here we will firstly create the schema for the listing model i.e for this 'listing' collection
// In Mongoose, creating new models means creating new collections.

// Creating the Model :-

const mongoose = require("mongoose");

const Review = require("./review");

// Here no need to create the connection again, as here we are only creating the model, but we will use that model in index.js file only
// SO we will require this current model directly in app.js

const Schema = mongoose.Schema;  // here we are creating a shortname for this mongoose.schems

const listingSchema = new Schema({
    title: {
        type: String,
        required: true,    
    },
    description: String,
    image: {
        url: String,
        filename: String,   // here we are storing the filename of the image which is stored in cloudinary, so that we can easily access that image from cloudinary using that filename because in cloudinary, we can access the image using its filename only, so here we are storing the filename of the image which is stored in cloudinary, so that we can easily access that image from cloudinary using that filename because in cloudinary, we can access the image using its filename only.
        // Here if we want to update or change the image of any listing, then we can easily delete the old image from cloudinary using this filename and then we can upload the new image to cloudinary and then we can update the URL and filename of that new image in our database for that listing, so that we can easily access that new image from cloudinary using that filename because in cloudinary, we can access the image using its filename only.
    },
    price: Number,
    location: String,
    country: String,
    reviews: [
        {
            //This tells Mongoose that the field will store a MongoDB ObjectId. An ObjectId is the unique identifier automatically generated by MongoDB for each document.
            // So, Instead of embedding the whole child document, you’re storing just its ID here.
            // ObjectIds act like foreign keys in relational databases.
            type: Schema.Types.ObjectId,    // it represents the type of _id actually
            ref: "Review"
            // This tells Mongoose which collection/model the ObjectId refers to. "Review" must match the name of the model to which this listing model is related
        }
    ],
    // So now each listing can have multiple reviews attach with it.

    // Each listing will only have 1 owner & not array of owners
    owner: {
        // Now this owner must refer to User model because any owner firstly must exists in database
        type: Schema.Types.ObjectId,
        ref: "User"
        // So here we are storing the id of the user document in the owner field of listing document, so that we can easily access the details of owner of that listing by using this owner field because this owner field is actually the reference to the user document which is the owner of that listing.
    },
    // here we are actually storing the GeoJSON data in this geometry field, so that we can easily access the coordinates of that listing from this geometry field to show the location of that listing on the map in the show page of that listing.
    geometry: {
        type: {
            type: String, // Don't do `{ geometry: { type: String } }`
            enum: ['Point'], // 'geometry.type' must be 'Point'
            required: true
        },
        coordinates: {
            type: [Number],   // here we will actually use array of 2 numbers
            required: true
        }
    }
});



// Here we are creating the post mongoose middleware
// So here we want to delete all the revies also whenever we delete any listing
// SO after deleting listing, we want to execute this post middleware actually.
listingSchema.post("findOneAndDelete", async (listing) => {
    // Now we will find all the reviews of this listing & will also delete those reviews
    if(listing && listing.reviews.length){    // it means that if listing exists & reviews exists for this listing
        let result = await Review.deleteMany({ _id: {$in: listing.reviews }});
        // But listing.reviews is likely an array of ObjectIds (the IDs of reviews belonging to that listing).
        // _id can only match a single value, not an array, unless you use the $in operator.
    }
}); 
// SO this post will run after the execution of findByIdAndDelete()
// After the deletion is complete, Mongoose calls your post("findOneAndDelete") hook.
// The deleted document is passed into this post middleware as the listing argument.




// Now we will create the listing model here
// So by-default mongoose will create a collection called as 'listings' for this model
const Listing = mongoose.model("Listing", listingSchema);


// Now we will export this Listing model, so that we can use it inside app.js file by requiring it.
module.exports = Listing; 
// Now we can require this model in app.js file using :- const Listing = require("./models/listing");

// Now here we know that each listing can have multiple reviews like 100 or 500 something
// SO here listings collection  is forming one to many relation with reviews collections here
// And as 1 listings will not have crores of reviews, so we will use array of reference of reviews in listing nodel schema here
// so we will store array of reviews documents id in the listing model schema here to set a relation b/w them.



// SO if we also want to delete all the orders of customer which we are deleting, i.e if we want to perform deletion in related colletions, we can do that by using Mongoose middleware.
// We can use 2 middlewares :-
//- Pre --> run before the query is executed to perform some task.
//- Post --> run after the query is executed to perform some task.

// Now in Pre & Post, this findByIdAndDelete() doesn't exists, so we can't use it with pre & post
// But findByIdAndDelete() is actually just the shorthand for findOneAndDelete() & findOneAndDelete() exits in pre & post
// SO we can use findOneAndDelete() in pre & post, which ultimately perform the work of findByIdAndDelete() only

// So actually no middleware exists for findByIdAndDelete(), but middleware exists for findOneAndDelete() 
// And findOneAndDelete() is itself an middleware for findByIdAndDelete(), so we can define the middleware for findOneAndDelete() & that middleware can be trigger using findOneAndDelete
// And findOneAndDelete can be trigger from findByIdAndDelete, so indirectly we are using findByIdAndDelete only.

// So if we use pre middleware for findOneAndDelete, & we are triggering this pre from findOneAndDelete, then it means that findByIdAndDelete is also triggering the pre middleware actually

